# Generated by Django 4.1.1 on 2023-06-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='count_product',
            field=models.IntegerField(default=1),
        ),
    ]
