# Generated by Django 4.1.1 on 2023-06-01 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0002_remove_product_category_remove_product_reviews_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
