# Generated by Django 4.1.1 on 2023-06-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0005_alter_product_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='grade',
            field=models.FloatField(default=0.0),
        ),
    ]
