# Generated by Django 4.1.1 on 2023-06-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0011_remove_product_short_name_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promotion',
            field=models.IntegerField(default=0),
        ),
    ]
