# Generated by Django 4.1.1 on 2023-06-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0014_remove_product_reviews_review_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.IntegerField(),
        ),
    ]
